#!/bin/sh

#  Copyright (c) 2016-2019 Yanhui Shen
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.

Ver="0.4.3"
Cols=$((`stty size | cut -d' ' -f2` - 6))
Rows=$((`stty size | cut -d' ' -f1` - 4))
Height=$(($Rows - 7))
PkgQuery="brew leaves | xargs brew desc"
PkgDelete="brew uninstall"
FmtDialog="dialog --checklist \"Leaf Formulas: %s\" $Rows $Cols $Height %s"

if ! type brew >/dev/null; then
    echo 'Error: "brew" is not installed.'
    exit
fi

if ! type dialog >/dev/null; then
    echo 'Error: "dialog" is not installed, try "brew install dialog" please.'
    exit
fi

for arg in "$@"; do
    case $arg in
        -v|--version)
        printf "$(basename $0) version $Ver\n"
        exit
        ;;
    esac
done

KeptLeaves=""
while true; do
    #==== refresh leaves ====
    echo "Querying..."
    AllLeaves=`eval $PkgQuery`
    NewLeaves=""
    nNewLeaves="0"

    IFS=$'\n'
    for line in $AllLeaves; do
        port=`echo $line | cut -d':' -f1`
        desc=`echo $line | cut -d':' -f2- | awk '{$1=$1};1' | sed "s/\"/'/g"`
        ret=`echo "$KeptLeaves" | grep "$port"`
        if [ -z "$ret" ]; then
            NewLeaves="$NewLeaves $port \"$desc\" off"
            nNewLeaves=$(($nNewLeaves + 1))
        fi
    done

    #==== show dialog ====
    if [ -z "$NewLeaves" ]; then
        echo "Nothing to do!"
        exit
    fi
    cmd=`printf $FmtDialog "$nNewLeaves" "$NewLeaves"`
    selections=`eval "$cmd 3>&2 2>&1 1>&3"`
    if [ $? -ne 0 ]; then
        echo "Canceled."
        exit
    fi

    #==== record old leaves ====
    KeptLeaves="$AllLeaves"

    #==== deinstall selected ====
    if [ -z $selections ]; then
        echo "No selection, quit."
        exit
    fi
    eval "$PkgDelete $selections"
done
